R/commonMachineLearningClustering.R
R/mlClusteringDensityBased.R
inst/qml/mlClusteringHierarchical.qml

+ jasp-stats/jasp-desktop#4222
+ jasp-stats/jasp-desktop#4214
+ jasp-stats/jasp-desktop#4350

Add pull requests to module

---

README.md

Currently, there is no information about the module in its github repository. @vandenman Should we add a small README for information?

An idea for a README

---

DESCRIPTION

Fixes https://github.com/jasp-stats/jasp-test-release/issues/1262, Fixes https://github.com/jasp-stats/jasp-test-release/issues/1266, Fixes https://github.com/jasp-stats/jasp-test-release/issues/1187

use vandenman/kknn as remote (hopefully temporarily)

---

R/mlRegressionBoosting.R

Should close https://github.com/jasp-stats/jasp-issues/issues/1387

Fix https://github.com/jasp-stats/jasp-issues/issues/1387

---

R/commonMachineLearningClustering.R
R/mlClusteringDensityBased.R
R/mlClusteringFuzzyCMeans.R
R/mlClusteringHierarchical.R
R/mlClusteringKMeans.R
R/mlClusteringRandomForest.R

This does not prevent the problem in https://github.com/jasp-stats/jasp-issues/issues/1073 from occurring, but at least shows a more informative error message.

Error message for distance matrix computation failure

---

.github/workflows/unittests.yml
R/commonMachineLearningClustering.R

@koenderks why did we install `rpart` from source again? Was it because the binary wasn't available?

use reuseable workflow

---

DESCRIPTION
R/commonMachineLearningRegression.R
inst/help/mlRegressionBoosting.md
inst/help/mlRegressionKnn.md
inst/help/mlRegressionKnn_nl.md
inst/help/mlRegressionNeuralNetwork.md
inst/help/mlRegressionRandomForest.md
inst/help/mlRegressionRandomForest_nl.md
inst/help/mlRegressionRegularized.md
inst/help/mlRegressionRegularized_nl.md
inst/help/mlregressiondecisiontree.md
inst/help/mlregressiondecisiontree_nl.md
inst/help/mlregressionsvm.md
inst/help/mlregressionsvm_nl.md
tests/testthat/test-mlclassificationrandomforest.R
tests/testthat/test-mlregressionboosting.R
tests/testthat/test-mlregressiondecisiontree.R
tests/testthat/test-mlregressionknn.R
tests/testthat/test-mlregressionneuralnetwork.R
tests/testthat/test-mlregressionrandomforest.R
tests/testthat/test-mlregressionregularized.R
tests/testthat/test-mlregressionsvm.R

+ Also update version in DESCRIPTION to 0.16.3

Change the column name of MAE to MAE / MAD

---

inst/qml/mlPrediction.qml

Fixes https://github.com/jasp-stats/jasp-test-release/issues/2200

Bad QML in Machine Learning Prediction

---

inst/qml/mlPrediction.qml

The change messed with the layout...

Revert qml change

---

R/commonMachineLearningRegression.R

Closes https://github.com/jasp-stats/jasp-issues/issues/2014

Put dependency on main table instead of results

---

R/commonMachineLearningClassification.R
R/commonMachineLearningClustering.R
R/mlClusteringDensityBased.R
R/mlClusteringFuzzyCMeans.R
R/mlClusteringHierarchical.R
R/mlClusteringKMeans.R
R/mlClusteringRandomForest.R
inst/Description.qml
inst/qml/mlClusteringDensityBased.qml
inst/qml/mlClusteringFuzzyCMeans.qml
inst/qml/mlClusteringHierarchical.qml
inst/qml/mlClusteringKMeans.qml
inst/qml/mlClusteringRandomForest.qml

Closes https://github.com/jasp-stats/jaspMachineLearning/issues/150

[0.17.3] Add cluster matrix plot

---

R/commonMachineLearningClassification.R
R/commonMachineLearningRegression.R

Closes https://github.com/jasp-stats/jasp-issues/issues/2416#issuecomment-1814483544

Check for .jaspML in save path

---

R/mlRegressionDecisionTree.R
R/mlRegressionNeuralNetwork.R

- Closes https://github.com/jasp-stats/jasp-test-release/issues/2503
- Closes https://github.com/jasp-stats/jasp-test-release/issues/2505

Fix test release issues

---

R/commonMachineLearningClassification.R
R/commonMachineLearningRegression.R

Add explainer to saved classification models

---

R/mlClassificationDecisionTree.R

- Closes https://github.com/jasp-stats/jasp-issues/issues/2596

Fix incorrect test set accuracy for dt if empty level

---

R/commonMachineLearningRegression.R
inst/help/mlRegressionBoosting.md
inst/help/mlRegressionKnn.md
inst/help/mlRegressionKnn_nl.md
inst/help/mlRegressionLinear.md
inst/help/mlRegressionLinear_nl.md
inst/help/mlRegressionNeuralNetwork.md
inst/help/mlRegressionRandomForest.md
inst/help/mlRegressionRandomForest_nl.md
inst/help/mlRegressionRegularized.md
inst/help/mlRegressionRegularized_nl.md
inst/help/mlregressiondecisiontree.md
inst/help/mlregressiondecisiontree_nl.md
inst/help/mlregressionsvm.md
inst/help/mlregressionsvm_nl.md
tests/testthat/test-mlregressionboosting.R
tests/testthat/test-mlregressiondecisiontree.R
tests/testthat/test-mlregressionknn.R
tests/testthat/test-mlregressionlinear.R
tests/testthat/test-mlregressionneuralnetwork.R
tests/testthat/test-mlregressionrandomforest.R
tests/testthat/test-mlregressionregularized.R
tests/testthat/test-mlregressionsvm.R

Closes https://github.com/jasp-stats/jasp-issues/issues/2619

Add scaled MSE to regression evaluation metrics

---

R/commonMachineLearningClassification.R
R/mlPrediction.R

Closes https://github.com/jasp-stats/INTERNAL-jasp/issues/2489

Remove nominaltext

---

R/commonMachineLearningClassification.R
inst/help/mlClassificationBoosting.md
inst/help/mlClassificationKnn.md
inst/help/mlClassificationLda.md
inst/help/mlClassificationNeuralNetwork.md
inst/help/mlClassificationRandomForest.md
inst/help/mlRegressionBoosting.md
inst/help/mlRegressionKnn.md
inst/help/mlRegressionLinear.md
inst/help/mlRegressionNeuralNetwork.md
inst/help/mlRegressionRandomForest.md
inst/help/mlRegressionRegularized.md
inst/help/mlclassificationdecisiontree.md
inst/help/mlclassificationsvm.md
inst/help/mlregressiondecisiontree.md
inst/help/mlregressionsvm.md
inst/qml/common/tables/ConfusionMatrix.qml
inst/qml/common/tables/ExplainPredictions.qml
inst/qml/common/ui/DataSplit.qml
inst/qml/mlClassificationDecisionTree.qml
inst/qml/mlClassificationSvm.qml
inst/qml/mlRegressionDecisionTree.qml
inst/qml/mlRegressionSvm.qml

- Option to transpose confusion matrix properly (feature)
- Show training and data validation split options for decision trees and support vector machines when optimised (bug)
- Add a placeholder text for the test set indicator
- Add more help on explaining predictions
The unit tests fail for Mac but this is not due to these changes.

Some features and bug fixes

---

R/mlClassificationBoosting.R

Closes https://github.com/jasp-stats/jasp-issues/issues/1838

Fix testset indicator bug in boosting classification

---

R/commonMachineLearningRegression.R
R/mlRegressionBoosting.R
R/mlRegressionDecisionTree.R
R/mlRegressionRandomForest.R

See https://forum.cogsci.nl/discussion/9338/feature-importance-in-machine-learning-module#latest

Add footnote to feature importance table defining dropout loss

---

R/commonMachineLearningClassification.R
R/commonMachineLearningClustering.R
R/commonMachineLearningRegression.R
inst/qml/common/analyses/regularized/VariablesFormRegularizedRegression.qml
inst/qml/common/ui/VariablesFormClassification.qml
inst/qml/common/ui/VariablesFormClustering.qml
inst/qml/common/ui/VariablesFormRegression.qml

These are changes I could easily spot. I am not ruling out that more will follow after testing.

Changes related to new variable conversion

---

R/commonMachineLearningRegression.R
R/mlClassificationBoosting.R
R/mlRegressionBoosting.R
R/mlRegressionRandomForest.R
inst/qml/common/ui/VariablesFormClassification.qml
inst/qml/common/ui/VariablesFormRegression.qml

- Closes https://github.com/jasp-stats/jasp-test-release/issues/2616
- Closes https://github.com/jasp-stats/jasp-test-release/issues/2615
- Closes https://github.com/jasp-stats/jasp-test-release/issues/2636

Bug fixes for release

---

R/commonMachineLearningClustering.R
R/commonMachineLearningRegression.R
R/mlRegressionRegularized.R
tests/testthat/test-mlclassificationboosting.R
tests/testthat/test-mlclassificationdecisiontree.R
tests/testthat/test-mlclassificationknn.R
tests/testthat/test-mlclassificationlda.R
tests/testthat/test-mlclassificationnaivebayes.R
tests/testthat/test-mlclassificationneuralnetwork.R
tests/testthat/test-mlclassificationrandomforest.R
tests/testthat/test-mlclassificationsvm.R
tests/testthat/test-mlclusteringdensitybased.R
tests/testthat/test-mlclusteringfuzzycmeans.R
tests/testthat/test-mlclusteringhierarchical.R
tests/testthat/test-mlclusteringkmeans.R
tests/testthat/test-mlclusteringmodelbased.R
tests/testthat/test-mlclusteringrandomforest.R
tests/testthat/test-mlregressionboosting.R
tests/testthat/test-mlregressiondecisiontree.R
tests/testthat/test-mlregressionknn.R
tests/testthat/test-mlregressionlinear.R
tests/testthat/test-mlregressionneuralnetwork.R
tests/testthat/test-mlregressionrandomforest.R
tests/testthat/test-mlregressionregularized.R
tests/testthat/test-mlregressionsvm.R

Fixes https://github.com/jasp-stats/jasp-test-release/issues/2680
Fixes https://github.com/jasp-stats/jasp-test-release/issues/2681
adjusting the unit tests was rather painful.

Changes for new variable types

---

R/mlPrediction.R
inst/Description.qml

@vandenman I think this should work like this, but I wasn't able to test the prediction analysis in JASP since I cannot build the dev module. Any other way to verify if I didn't break the data reading in this analysis? There is still the use of `dataset <- jaspBase::readDataSetByVariableTypes(options, c(optionNames, optionNamesAsNumeric))` in line 74 of `commonMachineLearningRegression.R`.

Data handling updates

---

R/commonMachineLearningClassification.R
R/commonMachineLearningRegression.R
R/mlPrediction.R

- Fixes https://forum.cogsci.nl/discussion/9555/prediction-with-classification-ml-model-numbers#latest

Store all variables in saved model

---

R/commonMachineLearningClustering.R

Fixes https://github.com/jasp-stats/jasp-issues/issues/3297

Fix both cluster means plot and table
